spring.application.name=taskmanagement
spring.profiles.active=dev

# Ép Swagger s?p x?p Tags và API theo b?ng ch? cái
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha